# Generated by Django 2.2 on 2020-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newsStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date of publication')),
                ('news_story_text', models.CharField(max_length=10000)),
            ],
        ),
    ]
